### ISSUE TITLE
Todo ~~before~~ after v9 nuget push

### ISSUE THREAD

**Issue by Thraka** [Thraka/SadConsole#262]
- [x] Investigate and fix #258  (ProcessMouse with a BorderConsole)
- [x] Update versions
- [ ] Documentation
  - [x] Update the API with latest build
  - [x] Create getting started content
  - [ ] Migrate the 4-part starter series
  - [ ] Port basic conceptual material from v8
- [x] Update MigrationNotes.txt to finish todo in there and clean up

**Comment by Thraka** [comment]
The rest of this is moving to V10
